### ISSUE TITLE
rgbToHex has problems with RGB value '0'

### ISSUE THREAD

**Issue by paulgeisler** [mexitek/phpColors#25]
It outputs single '0' in hex value. It should be a double zero '00'.

You need to replace
    **Line 197:** return implode( '', $hex );
    **with:**       return sprintf("%02s%02s%02s", $hex[0], $hex[1], $hex[2]);

**Comment by sqsinger1123** [comment]
Yep, I encountered this problem as well and created a different solution.
An alternative function rgbToHex solves this issue:

public static function rgbToHex( $rgb = array() ){
		 // Make sure it's RGB
		if(empty($rgb) || !isset($rgb["R"]) || !isset($rgb["G"]) || !isset($rgb["B"]) ) {
			throw new Exception("Param was not an RGB array");
		}
		// Convert RGB to HEX, explicit string conversions
		$hex[0] = (string)dechex( $rgb['R'] );
		$hex[1] = (string)dechex( $rgb['G'] );
		$hex[2] = (string)dechex( $rgb['B'] );

		// Make sure that 2 digits are allocated to each color {Sam added on 2015-02-14}
		$hex[0] = (strlen($hex[0]) == 1)? '0'.$hex[0] : $hex[0];
		$hex[1] = (strlen($hex[1]) == 1)? '0'.$hex[1] : $hex[1];
		$hex[2] = (strlen($hex[2]) == 1)? '0'.$hex[2] : $hex[2];

		return implode( '', $hex );
	}

**Comment by mexitek** [comment]
Feel free to submit a pull request so we can fix this issue.

**Comment by zachrattner** [comment]
I resolved this issue manually before realizing this thread existed. Here's how I fixed the issue: 

    public static function rgbToHex( $rgb = array() ){
         // Make sure it's RGB
        if(empty($rgb) || !isset($rgb["R"]) || !isset($rgb["G"]) || !isset($rgb["B"]) ) {
            throw new Exception("Param was not an RGB array");
        }

        // Convert RGB to HEX
        $hex[0] = str_pad(dechex($rgb['R']), 2, '0', STR_PAD_LEFT);
        $hex[1] = str_pad(dechex($rgb['G']), 2, '0', STR_PAD_LEFT);
        $hex[2] = str_pad(dechex($rgb['B']), 2, '0', STR_PAD_LEFT);

        return implode( '', $hex );

  }

**Comment by chemix** [comment]
is it time to close this issue? I think yes ;-)

**Comment by strarsis** [comment]
This issue still exists... `rgb(0, 158, 204)` is converted to `#09ecc`, but the correct value would be `#009ecc`.

**Comment by sqsinger1123** [comment]
I can take care of this. PR is up: https://github.com/mexitek/phpColors/pull/42

My apologies for long delay. Way back when I made my original comment with a suggested fix, I wasn't so familiar with Github, so I didn't know the right way to submit a PR. Glad to come back and contribute to this fix.
